### ISSUE TITLE
Add Serene Seasons after creating World Collapse

### ISSUE THREAD

**Issue by MaribelHearm** [StormDragon-64/Create-Plus#1]
I wanted to add Serene Seasons to the integration package, but when it crashed while creating the world, I checked the Serene Seasons conflicting mod and disabled it, but it didn't work

Error reporting：https://paste.ubuntu.com/p/yWBGW9j554/

**Comment by StormDragon-64** [comment]
It seems that Very Many Players and Serene Seasons are incompatible, even if you just use just those 2 mods alone. disabling vmp allowed me to use Serene Seasons with the pack, so maybe you disabled the wrong mod?
