### ISSUE TITLE
Mod won't open on modrinth launcher

### ISSUE THREAD

**Issue by jtitan1214** [StormDragon-64/Create-Plus#6]
**Describe the bug**
so i'm using modrinth launcher and so far whenever i try to use the mod, it tells me a instances is running but then suddenly stops before anything happens

**To Reproduce**
i just downloaded the pack from modrinth launcher and try launching it

 **Version** insert the version of Create+ you are using below.
Create+ 5.1.0c

**additional context**
this is the first time I've encountered this happening with launcher so I'm not sure if it pack or something else on my end, here's the logs i have on it https://mclo.gs/ZBBU1SD

**Comment by StormDragon-64** [comment]
What version of the modrinth app are you using? It should be at the bottom of the settings page.

**Comment by jtitan1214** [comment]
v0.8.5

**Comment by jtitan1214** [comment]
so i finally figured it out, and it turns out to be a AMD update issue, thanks to this video https://www.youtube.com/watch?v=mjc2UX7vmkQ
